name: Laravel Deploy

on:
  push:
    branches:
      - main

jobs:

  deploy:

    runs-on: self-hosted

    env:

      PHP: C:\PHP\php.exe

      SITE: C:\Users\Francisco\Desktop\test

      APPPOOL: test_github_actions


    steps:

    - name: Checkout
      uses: actions/checkout@v4


    - name: Install Composer
      run: |
        composer install `
          --no-dev `
          --prefer-dist `
          --optimize-autoloader


    - name: Install NPM
      run: |
        npm ci


    - name: Build assets
      run: |
        npm run build


    - name: Laravel migrations
      working-directory: ${{ env.SITE }}
      run: |
        & "${{ env.PHP }}" artisan migrate --force


    - name: Laravel optimize
      working-directory: ${{ env.SITE }}
      run: |
        & "${{ env.PHP }}" artisan optimize


    - name: Restart IIS
      run: |
        Import-Module WebAdministration

        Restart-WebAppPool `
          "${{ env.APPPOOL }}"
